# Generated by Django 4.2.7 on 2023-11-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='picture',
        ),
    ]
