# Generated by Django 4.2.7 on 2023-11-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_journal_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures_journal/', verbose_name='Изображение(превью)'),
        ),
    ]
