# Generated by Django 4.2.7 on 2023-11-07 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='фамилия')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_message_name', models.CharField(max_length=200, unique=True, verbose_name='название рассылки сообщения')),
                ('mailing_message_topic', models.CharField(blank=True, max_length=100, null=True, verbose_name='тема письма')),
                ('mailing_message_body', models.TextField(blank=True, null=True, verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_set_name', models.CharField(max_length=200, unique=True, verbose_name='названия рассылки настроек')),
                ('mailing_set_start_time', models.DateTimeField(blank=True, null=True, verbose_name='начало рассылки')),
                ('mailing_set_end_time', models.DateTimeField(blank=True, null=True, verbose_name='конец рассылки')),
                ('mailing_set_frequency', models.CharField(blank=True, choices=[('day', 'one_to_day'), ('week', 'one_to_week'), ('month', 'one_to_month')], max_length=15, null=True, verbose_name='периодичность')),
                ('mailing_set_is_status', models.CharField(blank=True, choices=[('create', 'mailing_create'), ('run', 'mailing_run'), ('finish', 'mailing_finish')], max_length=15, null=True, verbose_name='статус рассылки')),
                ('mailing_message_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingmessage', verbose_name='название рассылки сообщения')),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_log_last_try', models.DateTimeField(blank=True, default=0, null=True, verbose_name='последняя попытка')),
                ('mailing_log_is_status_try', models.BooleanField(blank=True, null=True, verbose_name='статус попытки')),
                ('mailing_log_response_server', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('mailing_log_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='email')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылок',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='mailing_set_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingsetting', verbose_name='названия рассылки'),
        ),
    ]
