# Generated by Django 4.2.7 on 2023-11-14 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='названия рассылки лога')),
                ('last_try', models.DateTimeField(blank=True, default=0, null=True, verbose_name='последняя попытка')),
                ('is_status_try', models.BooleanField(blank=True, null=True, verbose_name='статус попытки')),
                ('response_server', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('count_send_mail', models.IntegerField(default=0, verbose_name='количество отправленных рассылок')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылок',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Названия рассылки')),
                ('date_mailing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата рассылки')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='начало рассылки')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='конец рассылки')),
                ('frequency', models.CharField(blank=True, choices=[('day', 'one_to_day'), ('week', 'one_to_week'), ('month', 'one_to_month')], null=True, verbose_name='периодичность')),
                ('is_status', models.CharField(blank=True, choices=[('create', 'mailing_create'), ('run', 'mailing_run'), ('finish', 'mailing_finish')], null=True, verbose_name='статус рассылки')),
                ('mailing_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailinglog', verbose_name='mailing_log')),
                ('mailing_message_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingmessage', verbose_name='название рассылки сообщения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель рассылки')),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='фамилия')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('owner', models.ManyToManyField(to='mailing.mailingsetting', verbose_name='относится к рассылке')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
