# Generated by Django 4.2.7 on 2023-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='owner',
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='client',
            field=models.ManyToManyField(to='mailing.client', verbose_name='относится к рассылке'),
        ),
    ]
