# Generated by Django 4.2.7 on 2023-11-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsetting',
            name='mailing_set_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время рассылки'),
        ),
    ]
