# Generated by Django 4.2.7 on 2023-11-14 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_client_owner_mailingsetting_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsetting',
            name='next_time_run',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата следующей рассылки'),
        ),
    ]
