# Generated by Django 4.2.7 on 2023-11-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailingsetting_mailing_set_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing_set_name',
        ),
    ]
