# Generated by Django 4.2.7 on 2023-11-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_client_mailing_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mailing_set_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingsetting', verbose_name='названия рассылки'),
        ),
    ]
