# Generated by Django 4.2.7 on 2023-11-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailingsetting_next_time_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsetting',
            name='is_active_mailing',
            field=models.BooleanField(default=True, verbose_name='активность рассылки'),
        ),
    ]
