# Generated by Django 4.2.7 on 2023-11-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_client_created_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsetting',
            options={'permissions': (('change_only_owner', 'can change only owner of mailingsetting'),), 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
    ]
