# Generated by Django 4.2.7 on 2023-11-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_mailinglog_mailing_log_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing_log_last_try',
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='mailing_log_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='email'),
        ),
    ]
