# Generated by Django 4.2.7 on 2023-11-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_remove_client_mailing_log_last_try_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_List_name', models.CharField(max_length=150, unique=True, verbose_name='название списка клиентов')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.clientlist', verbose_name='список клиентов'),
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='client_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.clientlist', verbose_name='список клиентов'),
        ),
    ]
