# Generated by Django 4.2.7 on 2023-11-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_clientlist_client_client_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing_set_name',
        ),
    ]
