# Generated by Django 4.2.7 on 2023-11-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_remove_client_mailing_set_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlist',
            old_name='client_List_name',
            new_name='client_list_name',
        ),
    ]
