# Generated by Django 4.2.7 on 2023-11-08 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_rename_client_list_name_clientlist_client_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='mailing_log_email',
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='mailing_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailinglog', verbose_name='mailing_log'),
        ),
    ]
