# Generated by Django 4.2.7 on 2023-11-21 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0009_mailingmessage_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='created_client',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='count_send_mail',
            field=models.PositiveIntegerField(default=0, verbose_name='количество отправленных рассылок'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='is_status_try',
            field=models.BooleanField(default=False, verbose_name='статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='frequency',
            field=models.CharField(choices=[('day', 'one_to_day'), ('week', 'one_to_week'), ('month', 'one_to_month')], default=False, verbose_name='периодичность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='is_status',
            field=models.CharField(choices=[('create', 'mailing_create'), ('run', 'mailing_run'), ('finish', 'mailing_finish')], default='create', verbose_name='статус рассылки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель рассылки'),
            preserve_default=False,
        ),
    ]
