# Generated by Django 4.2.7 on 2023-11-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_remove_mailinglog_mailing_log_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsetting',
            name='mailing_set_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Названия рассылки'),
        ),
    ]
