# Generated by Django 4.2.7 on 2023-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_mailingsetting_mailing_set_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_list',
        ),
        migrations.AddField(
            model_name='client',
            name='client_list_m',
            field=models.ManyToManyField(to='mailing.clientlist'),
        ),
    ]
