# Generated by Django 4.2.7 on 2023-11-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_remove_client_client_list_m_client_client_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsetting',
            name='client_list',
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='client_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.clientlist', verbose_name='список клиентов'),
        ),
    ]
