# Generated by Django 4.2.7 on 2023-11-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_remove_mailingsetting_client_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLogTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_log_last_try', models.DateTimeField(blank=True, default=0, null=True, verbose_name='последняя попытка')),
                ('mailing_log_is_status_try', models.BooleanField(blank=True, null=True, verbose_name='статус попытки')),
                ('mailing_log_response_server', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientlist',
            options={'verbose_name': 'Список клиентов', 'verbose_name_plural': 'Списки клиентов'},
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='mailing_log_test',
            field=models.ManyToManyField(to='mailing.mailinglogtest'),
        ),
    ]
