# Generated by Django 4.2.7 on 2023-11-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0015_mailinglogtest_alter_clientlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsetting',
            name='mailing_log_test',
        ),
        migrations.DeleteModel(
            name='MailingLogTest',
        ),
    ]
