# Generated by Django 4.2.7 on 2023-11-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0016_remove_mailingsetting_mailing_log_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsetting',
            name='mailing_set_time',
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='mailing_set_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата рассылки'),
        ),
    ]
