# Generated by Django 4.2.7 on 2023-11-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_remove_mailingsetting_mailing_set_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='mailing_log_count_send_mail',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отправленных рассылок'),
        ),
    ]
