# Generated by Django 4.2.7 on 2023-11-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0018_mailinglog_mailing_log_count_send_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='mailing_log_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='названия рассылки лога'),
        ),
    ]
