# Generated by Django 4.2.7 on 2023-11-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0020_mailingsetting_mailing_set_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mailing_set_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingsetting', verbose_name='создатель клиента'),
        ),
    ]
