# Generated by Django 4.2.7 on 2023-11-12 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0021_client_mailing_set_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing_set_owner',
        ),
        migrations.AddField(
            model_name='client',
            name='client_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создатель клиента'),
        ),
    ]
